### PR TITLE
Camera: made one world unit equal to one tile

### PR DESCRIPTION
**Pull request by Salzimus**
This change aims to make it easier to reason about size and distance and to avoid magic numbers.
Additionally the camera's movement has been moved to the PostUpdate stage to prevent some unpredictable behavior.

### CODE REVIEW

**Comment by mwbryant** [comment]
My problem with this camera mode is things stay the same real size at different resolutions but what is actually visible in the game changes (ie full screen now lets you see more of the world and the ui is misplaced, see screenshots).  Arguably the game is currently not resize-able but I think it would be nice to keep that as an option for the future.  The rest of the changes are great though and I'll keep the pixel size as a coordinate system.

Normal view:
windowed

Full screen:
fullscreen

Wild Resolution:
bad_resoution

**Comment by salomon-hhs** [comment]
I was also thinking about how resizing would change things. The UI would be an easy fix but otherwise it seems like either things will display at the proper pixel size or you will have to deal with how much you can see on the screen changing, as you mentioned. Perhaps the window size could have an effect on pixel scale?

**Comment by Salzimus** [comment]
I was also thinking about how resizing would change things. The UI would be an easy fix but otherwise it seems like either things will display at the proper pixel size or you will have to deal with how much you can see on the screen changing, as you mentioned. Perhaps the window size could have an effect on pixel scale?

**Comment by mwbryant** [comment]
This is the behavior that camera scaling mode none gives.  I think we want the game to stretch and squeeze when the game is resized so you always see the same gameplay elements regardless of window size.  I kept all your changes so we now use the new coords systems.  At the intended resolution the game will be exactly at the right pixel size still.

I'm planning on redoing the ui to use bevy ui this week.  I have solved it finally on a side project.

**Pull request merged**
